myfile:common.o

	#gcc -o myfile greeting.o
        g++ -c -o myfile common.o common.c   common.h

common.o:common.c common.h
  
	gcc -c common.c common.h

clean:rm myfile greeting.o my_print.o my_print2.o



#g++ -c -o common.o common.c   common.h
